### ISSUE TITLE
i have problem, when i want to start tuxcut

### ISSUE THREAD

**Issue by M16Yusuf** [a-atalla/tuxcut#15]
I installed tuxcut for ubuntu, but I had difficulty running the application. 

`systemctl` `start` `tuxcut`

I have run "sytemctl start tuxcut" on my terminal but I get an error: 

`Failed` `to` `start` `tuxcut.service:` `Unit` `tuxcut.service` `not` `found.`

what should i do ?

**Comment by AhmedEhabH** [comment]
what's the solution?

**Comment by mainmast-git** [comment]
The issue is that you are trying to start tuxcut.service, but currently it is called tuxcutd.service.

I found the solution for why Tuxcut won't open, atleast if you are running Tuxcut in Kali Linux but give it a try. Run the following command in your terminal:

```shell
systemctl disable --now tuxcutd.service && systemctl enable --now tuxcutd.service && tuxcut
```
