### ISSUE TITLE
Tuxcut fails to launch.

### ISSUE THREAD

**Issue by Xeddius** [a-atalla/tuxcut#3]
`Python2 tuxcut.py`
and
`Python3 tuxcut.py`
both cause:
`File "tuxcut.py", line 13
    print lang
             ^
SyntaxError: Missing parentheses in call to 'print'
`

**Comment by a-atalla** [comment]
which version/branch is this ?
please get the latest from [Here](https://github.com/a-atalla/tuxcut/releases)
