### ISSUE TITLE
This Version of Tuxcut is expired 

### ISSUE THREAD

**Issue by HemaZ** [a-atalla/tuxcut#6]
I downloaded the latest release .deb package from this link 
https://github.com/a-atalla/tuxcut/releases
after installing it shows this message.
https://i.imgur.com/qGAJHDP.png

**Comment by a-atalla** [comment]
could you please provide the file name you downloaded

**Comment by HemaZ** [comment]
@a-atalla  tuxcut_6.0_amd64.deb

**Comment by MathPie** [comment]
Same Issue

**Comment by 66FAYE** [comment]
same issue +1

**Comment by aaditpant** [comment]
i downloaded the tuxcut_6.0beta2_amd64.deb and got the same issue i.e the version of tuxcut is expired.

**Comment by ekevjn** [comment]
any update?

**Comment by aminelch** [comment]
up !!!

**Comment by abdoub560** [comment]
upppppppp

**Comment by gonewild2018** [comment]
I've got same problem :)

**Comment by eslamdawood** [comment]
@a-atalla it's same problem with tuxcut_6.0beta2_amd64.deb ? is there any update to solve that problem ?

**Comment by sayfeddinekhalili** [comment]
change your date to 2016

**Comment by emaruri** [comment]
tuxcutd.py

if dt.datetime.today().year == 2018:
    logger.info('This is a BETA version is expired')
    sys.exit()

**Comment by a-atalla** [comment]
new packages uploaded... clising this
