### ISSUE TITLE
No deb version for version 6 pro

### ISSUE THREAD

**Issue by KIMWW** [a-atalla/tuxcut#8]
There is a deb file for version 6 beta but how can I have a deb file for version 6 pro, there is only the  source code. Can someone explain me?? I am a newbie and I don't understand.

**Comment by a-atalla** [comment]
sorry for the confusion, there were a problem in the packages , will rebuild again soon

**Comment by gregodadone** [comment]
I'm having problems compiling this code, can you rebuild please?

**Comment by alienflorina** [comment]
Still there's no deb version 6. Can't use the beta2 since it gives me version expired error. Build it plzzz

**Comment by KIMWW** [comment]
Me too I'd love to have it!
I suppose a-atalla is busy with something else...

**Comment by alienflorina** [comment]
I would do it myself if I knew how . 😆 Is there an alternative for gnome 3.28?

**Comment by a-atalla** [comment]
new packages uploaded and documents updated to build yourself
sorry for delay
