### ISSUE TITLE
Protection mode cannot be enabled

### ISSUE THREAD

**Issue by lukalafaye** [a-atalla/tuxcut#9]
I got this error:
`TuxCut couldn't detect the gateway MAC address
The protection mode couldn't be enabled`

**Comment by aminelch** [comment]
same outpout

**Comment by h4xw4r** [comment]
same here on Bionic Beaver

**Comment by lukalafaye** [comment]
@aminelch @h4xw4r 

I fixed the issue by running `tuxcut` as root and selecting the correct wireless network interface. When running the program with `sudo ./tuxcut.py`, you can select another interface. `io` is not the correct one in your case.

**Comment by a-atalla** [comment]
please test the latest packages and report if any issues
